# 条款08：别让异常逃离析构函数

​		Prevent exceptions from leaving destructors

​	如果我们使用容器放置一些数据，这些数据可能在析构函数中吐出异常，那么容器自动析构时，会去销毁其中各个数据，万一其中的一些出现异常，比如两个以上，C++会出现不明确的行为。

​	所以最好不要在析构函数中吐出异常；

​	那么如果真的有这样的需求怎么办？考虑这样的例子：

````c++
class DBConnection{
public:
	...
    static DBConnection create();			// 此函数返回 DBConnection 对象
    
    void close();							// 关闭联机，失败则抛出异常
};
````

​	为了保证用户不忘记在 `DBConnection` 上调用 `close()`，一个合理的想法是创建一个用来管理 `DBConnection` 资源的 class，并在析构函数中调用 `close()` ：

````c++
class DBConn{
public:
	...
	~DBConn()			// 确保数据库连接总会被关闭
	{	
		db.close();
	}
private:
	DBConnection db;
};
````

​	那么用户就可以这样写：

````c++
DBConn dbc(DBConnection::create());
````

​	可见，在 DBConn 对象的析构函数中调用了 close，这个函数是可能抛出异常的，我们可以这样处理：

- 如果 `close` 抛出异常就结束程序：

    ````c++
    DBConn::~DBConn()
    {
    	try{ db.close(); }
    	catch (...){
    		std::abort();
    	}
    }	
    ````

- 吞下因调用 `close` 而发生的异常

    ````c++
    DBConn::~DBConn()
    {
    	try { db.close(); }
    	catch (...){
    		制作运转记录，记下对close调用失败
    	}
    }
    ````

    一般来说，将异常吞下是坏消息，因为其压制了 “某些动作失败” 的重要信息，然而有时候吞下异常也比负担 “草率结束程序” 或 “不明确行为带来的风险” 好。为了让这成为一个可行方案，程序必须能够继续执行，即使在遭遇并忽略一个错误之后。

​	但是这两种方法都无法对 “导致`close`抛出异常” 的情况做出反应；

​	一个更好的策略是重新设计 DBConn 接口，使其客户有机会对可能出现的问题做出反应。例如 DBConn 自己可以提供一个 close 函数，因而赋予客户一个机会得以处理 “因该操作而发生的异常”。DBConn 也可以追踪其所管理之 DBConnection 是否已被关闭，并在答案为否的情况下由其析构函数关闭之。这可放置遗失数据库连接。然而如果 DBConnection 析构函数调用 close 失败，我们又将退回 “强迫结束程序“ 或 “吞下异常” 的老路：

````c++
class DBConn{
public:
	...
	void close()
	{
		db.close();
		closed = true;
	}
	~DBConn()
	{
		if (!closed){
			try {
				db.close();	
			}
			catch (...){
				// 结束程序或者吞下异常
            }
		}
	}
private:
	DBConnection db;
	bool closed;
};
````

---





## 请记住

- 析构函数绝不要吐出异常。如果一个被析构函数调用的函数可能抛出异常，析构函数应该捕获任何异常，然后吞下它们（不传播）或结束程序；
- 如果客户需要对某个操作函数运行期间抛出的异常做出反应，那么 class 应该提供一个普通函数（而非析构函数）执行该操作；